---
title: "Adjustment_Covariate"
author: "Isobel Beasley"
date: "16/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 100, 
                      echo=TRUE, 
                      warning=FALSE, message=FALSE, eval = TRUE,
                      fig.show=TRUE, fig.width= 9,fig.height= 8,fig.align='center', out.width = '100%', fig.path= 'Figures/', fig.pos = 'H')
```

## Load Required Packages

```{r, message=FALSE, warning=FALSE}
library(ttBulk)
library(dplyr)
library(ggplot2)
```

## Load Data

```{r}
load("/stornext/Home/data/allstaff/b/beasley.i/TABI/dev/ed_PC_TCGA.rda")

#Putting Purity Score Into Groups
ed_PC_TCGA <-ed_PC_TCGA %>% mutate (
  purity.group = case_when(
  0.70<=purity.score & purity.score<0.75 ~ "0.70<=purity.score<0.75",
  0.75<=purity.score & purity.score<0.80 ~ "0.75<=purity.score<0.80",
  0.80<=purity.score & purity.score<0.85 ~ "0.80<=purity.score<0.85",
  0.85<=purity.score & purity.score<0.90 ~ "0.85<=purity.score<0.90"))
```

# PCA Analysis 

## Using ttBulk

```{r}
#Reduce Dimensions using PCA Analysis (first six PC components)
PCA_PC_TCGA<-ed_PC_TCGA %>% 
  filter(is.na(transcript)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% 
  reduce_dimensions(.element=Sample.ID, .feature=transcript, .abundance=`read count normalised`, method="PCA", .dims=6)
```

## Plotting

```{r}
#Create Plotting Function 
plot_pairs_PC <- function(x) {
  print(PCA_PC_TCGA %>% 
    mutate_at(.cols=x, .funs=as.factor) %>%
    select(contains("PC"), Sample.ID, x) %>%
    distinct() %>%
    GGally::ggpairs(columns = 1:6, ggplot2::aes_string(colour=x)) + ggtitle(x))
}
```

```{r, results="hide", message=FALSE, warning=FALSE}
impact_results<-c("TSS", "vial", "PlateId", "BatchId", "purity.group", "subtype_avgDNA_purity", "subtype_avgRNA_purity","subtype_ISOpure_purity" , "subtype_ABSOLUTE_purity", "subtype_CLONET_purity") 

sapply(impact_results, plot_pairs_PC)
```

```{r, eval=FALSE}
adjust <- function(x) {
   Formula<- as.formula(paste("~", "CAPRA_S", "+", x))
   ed_PC_TCGA <-ed_PC_TCGA %>% 
     filter(is.na(transcript)==F, is.na(x)==F, is.na(`CAPRA-S`)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% 
     rename(CAPRA_S = `CAPRA-S`) 
   ed_PC_TCGA <-inner_join(ed_PC_TCGA, ed_PC_TCGA %>% distinct(Sample.ID, TSS) %>% count(TSS) %>% arrange(n) %>% filter(n > 2)  )
   adjust_abundance(.data=ed_PC_TCGA, .formula=Formula, .sample=Sample.ID, .transcript=transcript, .abundance=`read count normalised`, action="get")
}




ed_PC_TCGA_<-ed_PC_TCGA %>% 
     filter(is.na(transcript)==F, is.na(`CAPRA-S`)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% 
     rename(CAPRA_S = `CAPRA-S`) 
  e<-ed_PC_TCGA_1 %>% distinct(Sample.ID, TSS) %>% count(TSS) %>% arrange(n) %>% filter(n > 2) 
  
  
  
   ed_PC_TCGA_1 <-ed_PC_TCGA %>% 
     filter(is.na(transcript)==F, is.na(TSS)==F, is.na(`CAPRA-S`)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% 
     rename(CAPRA_S = `CAPRA-S`) 
   
 ed_PC_TCGA_1 <- inner_join(ed_PC_TCGA_1, ed_PC_TCGA_1 %>% distinct(Sample.ID, TSS) %>% count(TSS) %>% arrange(n) %>% filter(n > 2))


 
  

#Currently working 
 
#Purity.group 
a1<-adjust_abundance(
  .data=ed_PC_TCGA %>% 
    filter(is.na(purity.group)==F, is.na(transcript)==F, is.na(`CAPRA-S`)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% 
     rename(CAPRA_S = `CAPRA-S`) , 
  .formula=~CAPRA_S +purity.group, .sample=Sample.ID, .transcript=transcript, .abundance=`read count normalised`, action="get")

#BatchID
Batch<-adjust_abundance(.data=ed_PC_TCGA %>% 
                       filter(is.na(BatchId)==F, is.na(transcript)==F, is.na(`CAPRA-S`)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% 
     rename(CAPRA_S = `CAPRA-S`) , .formula=~CAPRA_S +BatchId, .sample=Sample.ID, .transcript=transcript, .abundance=`read count normalised`, action="get")





ed_PC_TCGA_1 <-ed_PC_TCGA %>% filter(is.na(transcript)==F, is.na(`CAPRA-S`)==F, is.na(vial)==F, is.na(Sample.ID)==F, is.na(`read count normalised`)==F) %>% rename(CAPRA_S = `CAPRA-S`)
   adjust_abundance(.data=ed_PC_TCGA_1, .formula=~CAPRA_S +TSS, .sample=Sample.ID, .transcript=transcript, .abundance=`read count normalised`, action="get")
   
```

