---
title: "Testing model deconstruction"
output: html_notebook
---


```{r setup}
devtools::load_all(".")
library(rstan)
library(here)
library(shinystan)
library(tidyverse)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r}
model = stan_model(file = here("dev","DE_sigmoid_deconstruct.stan"))
```


```{r}
data = full_simulator(10,20,
                        horseshoe_hyperprior_params(10), 
                        default_intercept_params(0.5, 0.3), #intercept here is the location of the inflection point
                        sigmoid_link_params(5,3), 
                        #linear_link_params(),
                        #normal_likelihood_params(1)
                        neg_binomial_likelihood_params(2)
                        )
plot_simulated(data)

fit <- sampling(model, data = data$observed, control = list(adapt_delta = 0.9))

evaluation_summary(rstan::extract(fit),true_params = data$true)
```


```{r}
n_plots = 5
for(i in 1:n_plots) {
  n_genes = 1000
  data = full_simulator(n_genes,20,
                          horseshoe_hyperprior_params(5), 
                          default_intercept_params(0, 1), #intercept here is the location of the inflection point
                          logsigmoid_link_params(log_y_cross_mean = log(1 / n_genes), log_y_cross_sigma = 2, sum_to_zero_sigma = 1/n_genes), 
                          dirichlet_multinom_likelihood_params(xi_sigma = 0.1)
                          )
  plot_simulated(data) %>% print()
}
```



