---
title: "No_Data_Generated_Quantities"
author: "Isobel Beasley"
date: "Last Edited 4/1/2019"
output: 
html_document: 
  toc: yes
  toc_depth: 3
  number_sections: true
  theme: readable
  highlight: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, fig.height=10, fig.width = 12, warning=FALSE, message=FALSE, eval = TRUE, fig.show=TRUE, fig.align='center', out.width = '100%')
```


```{r}
#Load required packages
library(TABI)
library(dplyr)
library(ggplot2)
library(tibble)
library(tidybayes)
library(rstan)
#Load data - normalised, with na removed and CAPRA_S 8 place in group CAPRA_S 7
normalised_PC_TCGA <- readRDS("/stornext/Home/data/allstaff/b/beasley.i/TABI/compress_normalised_narm_TCGA.rds")
```

## Run TABI (blind to data selected)

```{r}
gen_data<-TABI_glm(
  formula = ~CAPRA_S, 
  data  = normalised_PC_TCGA %>% #from normalised and na rm data 
    filter(transcript =="A1BG") %>% #Select gene for testing 
    select(CAPRA_S, `read_count normalised`), #Select only required columns
  prop_DE =  0.1,
  scale_DE =5,
  model = rstan::stan_model("~/TABI/inst/stan/DE_sigmoid_fixed_log_space_fit_vert_trans.stan", auto_write = F), #Select model (with stricter priors, for #beta1_z[1,1]  n(0,1), and inflection = n(0,1))
  prior_only = 1 #Prevent analysis of data / generate with disregard to data
)
```

## Show that fit is unrelated to data 

```{r}
#Note that parameters hover around zero (expected exception in y_cross_raw as it required/restricted to be y_cross + A)
traceplot(gen_data$fit)


#Summary of fit  / equation parameters
as.data.frame( #Initially coherse into data frame so row names (which are parameters) are kept
  summary(
    gen_data$fit) #Take the stanfit model
  $summary) %>% #Extract summary of those 
      rownames_to_column("parameters") %>% #Make row names (which are names of paramters) explicit column 
      filter(!grepl("y_hat", parameters), !grepl("y_gen", parameters), !grepl("phi", parameters)) #Remove rows with y_hat and y_gen and phi (these are generted per sample - would make this a really large table)
```
## Plot distribution of generated data

```{r}
#Create tibble for plotting
gen_data_plot<-left_join( #Combine 
  tidybayes::gather_draws(gen_data$fit, #All extracted draws of generated y_values
                                                 y_gen[T,G]), 
                         gen_data$input.X %>% mutate(T = 1:n())) #Inputted CAPRA_S score with sample number

#Plot y_gen value against CAPRA_S
gen_data_plot %>% 
  ggplot(aes(x=CAPRA_S,  y=.value)) + 
  geom_point() 

```

## Compare Posterior of inflection and slope

```{r}
pairs(gen_data$fit, pars=c("inflection[1]", "beta[2,1]"))
```