---
title: "TABI_Test_No_Relationship"
author: "Isobel Beasley"
date: "Last Updated 23/12/2019"
output: 
html_document: 
  toc: yes
  toc_depth: 3
  number_sections: true
  theme: readable
  highlight: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, fig.height=10, fig.width = 12, warning=FALSE, message=FALSE, eval = TRUE, fig.show=TRUE, fig.align='center', out.width = '100%')
```

```{r loading packages}
#Load Required Packages
library(ggplot2)
library(dplyr)
library(rstan)
#TABI
if("package:TABI" %in% search()) detach("package:TABI", unload=TRUE, force=TRUE); library(TABI)  
```

# Simulate Data with no change in Gene Transcription Across CAPRA_S levels 

```{r}

x_val=seq(from=-10, to=10, by=0.01) #CAPRA_S simulated values
CAPRA_S=x_val
y_sim<- rnbinom(length(x_val), mu=exp(3), size=2)  #Assume gene count follows a negative binomial 

#Plot of simulated data in log space
ggplot(aes(x=x_val, y=y_sim), data=data.frame(x_val, y_sim)) +
  geom_point() + 
  scale_y_log10() 

```

# Run on TABI 

```{r}
#Create Data Frame for TABI
Test = data.frame(CAPRA_S = x_val, gene = y_sim)

#Run TABI 
Test_No_Relationship<-TABI_glm(formula= ~CAPRA_S, 
         data= Test, 
         prop_DE =0.1, 
         scale_DE = 5, 
         #Choose model with simplified overdispersion, vertica
         model= rstan::stan_model("/stornext/Home/data/allstaff/b/beasley.i/TABI/inst/stan/DE_sigmoid_one_gene_vert_log_space_od.stan", auto_write = F))

```
