---
title: "study_over_overdispersion"
author: "Mangiola Stefano"
date: "19/06/2018"
output:
  html_document:
    toc: yes
    toc_depth: 3
    code_folding: hide
  github_document:
    toc: yes
    toc_depth: 3
linkcolor: magenta
urlcolor: magenta
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, results='hide', include=FALSE}
library(foreach)
library(tidyverse)
library(rstan)
library(gridExtra)
library(tidybayes)
```


```{r global variables}

real_mean = seq(1, 10, 1)*100
samples = 40
exposure = round(rnorm(samples, 10000, 100))

```


```{r declare functions}

multinomial_pure = function(){
	
	model_simple = "
	data{
	int T;
	int G;
	int y[T, G];
	int exposure[T];
	}
	parameters{
	vector[G] mu;
	}
	transformed parameters{
		vector[G] mu_softmax = softmax(mu);
	}
	model{
	sum(mu) ~ normal(0, 0.001 * G);
	for(t in 1:T) y[t] ~ multinomial( mu_softmax );
	}
	generated quantities{
	int y_gen[T, G];
	for(t in 1:T) y_gen[t] = multinomial_rng( mu_softmax, exposure[t] );
	
	}
	
	"
	fit = stan(
		model_code = model_simple,
		data = list(
			T = samples,
			G = length(real_mean),
			y = y,
			exposure = exposure
		),
		cores = 4,
		iter = 800
	)
	
	list(
		fit = fit,
		getn = fit %>%
			gather_samples(y_gen[sample_idx, gene_idx] ) %>%
			mean_qi() 
	)
	
}

dirichlet_multinomial = function(){
	
	model_simple = "
	functions{
		real dirichlet_multinomial_lpmf(int[] y, vector alpha) {
	  	real alpha_plus = sum(alpha);
	
	    return lgamma(alpha_plus) + sum(lgamma(alpha + to_vector(y)))
	                - lgamma(alpha_plus+sum(y)) - sum(lgamma(alpha));
	  }
	
	 	int[] dirichlet_multinomial_rng(vector alpha, int exposure) {
	    return multinomial_rng(dirichlet_rng(alpha), exposure);
	  }
	}
	data{
	int T;
	int G;
	int y[T, G];
	int exposure[T];
	}
	parameters{
	vector[G] mu;
// Overdispersion of Dirichlet-multinomial
	real<lower=0> xi_z;
	
	}
	transformed parameters{
		vector[G] mu_softmax = softmax(mu);

	// Calculate precision
	xi = xi_z * G * 10

	}
	model{
	sum(mu) ~ normal(0, 0.001 * G);
	for(t in 1:T) y[t] ~ dirichlet_multinomial( xi * mu_softmax );
	}
	generated quantities{
	int y_gen[T, G];
	for(t in 1:T) y_gen[t] = dirichlet_multinomial_rng(  xi * mu_softmax, exposure[t] );
	
	}
	
	"
	fit = stan(
		model_code = model_simple,
		data = list(
			T = samples,
			G = length(real_mean),
			y = y,
			exposure = exposure
		),
		cores = 4,
		iter = 800
	)
	
	list(
		fit = fit,
		getn = fit %>%
			gather_samples(y_gen[sample_idx, gene_idx] ) %>%
			mean_qi() 
	)
	
}


logNormal_multinomial= function(){
	
	model_simple = "
		functions{
			real gamma_log_lpdf(vector x_log, real a, real b){

				vector[rows(x_log)] jacob = x_log; //jacobian
				real norm_constant = a * log(b) -lgamma(a);
				real a_minus_1 = a-1;
				return sum( jacob ) + norm_constant * rows(x_log) + sum(  x_log * a_minus_1 - exp(x_log) * b ) ;

			}
		}
		data{
		int T;
		int G;
		int y[T, G];
	int exposure[T];

		}
		parameters{
		vector[G] alpha_z[T];
		vector[G] mu;
		vector<lower=0>[2] mu_prior;

		real<lower=0> sigma;
		}
		transformed parameters{
		vector[G] mu_softmax = softmax(mu);
		
		vector[G] alpha[T];

		for(t in 1:T) alpha[t] = mu + alpha_z[t] * sigma;
		}
		model{
		mu ~ gamma_log(mu_prior[1]+1, mu_prior[2]);
		mu_prior ~ exponential(1);
		sum(mu) ~ normal(0, 0.001*G);

		for(t in 1:T) alpha_z[t] ~ normal(0, 1);
		//for(t in 1:T) sum(alpha_z[t]) ~ normal(0, 0.001 * G);

		for(t in 1:T) y[t] ~ multinomial( softmax( alpha[t] ) );
		
		sigma ~ cauchy(0, 2.5);
		}
		generated quantities{
		int y_gen[T, G];
		vector[G] mu_od;
		vector[G] gamma_log_sampling;
		for(g in 1:G) mu_od[g] = normal_rng( mu[g] , sigma );
		for(t in 1:T) y_gen[t] = multinomial_rng( softmax( mu_od ), exposure[t] );

		for(g in 1:G) gamma_log_sampling[g] = log( gamma_rng(mu_prior[1]+1, mu_prior[2]) );
		
		}
	
	"
	
	fit = stan(
		model_code = model_simple,
		data = list(
			T = samples,
			G = length(real_mean),
			y = y,
			exposure = exposure
		),
		cores = 4,
		iter = 800
	)
	
	list(
		fit = fit,
		getn = fit %>%
			gather_samples(y_gen[sample_idx, gene_idx] ) %>%
			mean_qi() 
	)
	
}

logNormal_multinomial_2= function(){
	
	model_simple = "
		data{
		int T;
		int G;
		int y[T, G];
	int exposure[T];

		}
		parameters{
		vector[G] alpha_z;
		vector[G] mu;
		real sigma;
		}
		transformed parameters{
		vector[G] mu_softmax = softmax(mu);
		real<lower=0> exp_sigma = exp(sigma);

		vector[G] alpha = mu + alpha_z * exp_sigma;
		}
		model{
		
		alpha_z ~ normal(0, 1);
		
		sum(mu) ~ normal(0, 0.001 * G);
		for(t in 1:T) y[t] ~ multinomial( softmax( alpha ) );
		
		sigma ~ normal(0, 5);
		}
		generated quantities{
		int y_gen[T, G];
		vector[G] mu_od;
		for(g in 1:G) mu_od[g] = normal_rng( mu[g] , exp_sigma );
		for(t in 1:T) y_gen[t] = multinomial_rng( softmax( mu_od ), exposure[t] );
		
		}
	
	"
	
	fit = stan(
		model_code = model_simple,
		data = list(
			T = samples,
			G = length(real_mean),
			y = y,
			exposure = exposure
		),
		cores = 4,
		iter = 800
	)
	
	list(
		fit = fit,
		getn = fit %>%
			gather_samples(y_gen[sample_idx, gene_idx] ) %>%
			mean_qi() 
	)
	
}

multinomial_over_overdispersed= function(){
	
	model_simple = "
	data{
	int T;
	int G;
	int y[T, G];
	int exposure[T];

	}
	parameters{
	vector[G] alpha_z[T];
	vector[G] mu;
	real sigma;
	real sigma_slope;

	}
	transformed parameters{
	vector[G] mu_softmax = softmax(mu);
	vector[G] alpha[T];

	for(t in 1:T) alpha[t] = mu + alpha_z[t] .* exp( sigma + mu * sigma_slope) ;
	
	}
	model{
	
	for(t in 1:T) alpha_z[t] ~ normal(0, 1);
	
	sum(mu) ~ normal(0, 0.001 * G);
	for(t in 1:T) y[t] ~ multinomial( softmax( alpha[t] ) );
	
	sigma ~ cauchy(0, 2.5);
	sigma_slope ~ normal(0,5);
	}

	generated quantities{
	int y_gen[T, G];
	vector[G] mu_od;
	for(g in 1:G) mu_od[g] = normal_rng( mu[g] , exp( sigma + mu[g] * sigma_slope) );
	for(t in 1:T) y_gen[t] = multinomial_rng( softmax( mu_od ), exposure[t] );
	
	}
	
	"
	
	fit = stan(
		model_code = model_simple,
		data = list(
			T = samples,
			G = length(real_mean),
			y = y,
			exposure = exposure
		),
		cores = 4,
		iter = 800
	)
	
	list(
		fit = fit,
		getn = fit %>%
			gather_samples(y_gen[sample_idx, gene_idx] ) %>%
			mean_qi() 
	)
	
}

negative_binomial= function(){
	
	model_simple = "
	data{
	int T;
	int G;
	int y[T, G];

	}
	parameters{
	vector[G] alpha_z[T];
	vector[G] mu;
	real<lower=0> sigma;
	vector[T] exposure;

	}
	transformed parameters{
	vector[G] mu_softmax = softmax(mu);
	}
	model{
	
	for(t in 1:T) alpha_z[t] ~ normal(0, 1);
	for(t in 1:T) y[t] ~ neg_binomial_2_log( exposure[t] + mu, sigma );
	
	sigma ~ cauchy(0, 2.5);
	exposure ~ cauchy(0, 2.5);
	}
	generated quantities{
	int y_gen[T, G];

	for(t in 1:T) for(g in 1:G) y_gen[t,g] = neg_binomial_2_log_rng( exposure[t] + mu[g], sigma);
	
	}
	
	"
	
	fit = stan(
		model_code = model_simple,
		data = list(
			T = samples,
			G = length(real_mean),
			y = y
		),
		cores = 4,
		iter = 800
	)
	
	list(
		fit = fit,
		getn = fit %>%
			gather_samples(y_gen[sample_idx, gene_idx] ) %>%
			mean_qi() 
	)
	
}



plot_gen = function(x){
	
		my_noise = rnorm( x %>% nrow(), 0, 0.1	)

		
	x %>%
		
		# Add gene names
		left_join(
			tibble(
				gene_idx = 1:ncol(y),
				gene =     colnames(y)
			),
			by = "gene_idx"
		) %>%
		
		# Attach observed y
		left_join(
			y %>% 
				mutate(sample_idx = 1:!!samples) %>% 
				gather(gene_idx, observed, -sample_idx) %>% 
				mutate(gene_idx = as.integer(gene_idx)),
			by = c("sample_idx", "gene_idx")
		) %>%
		
		# Plot
		ggplot(aes(x=gene_idx+my_noise, y=observed, group=interaction(gene_idx, sample_idx))) +
		geom_point(color="red") +
		geom_errorbar(aes(ymin=conf.low, ymax=conf.high), width = 0, alpha=0.2) +
		theme_bw()
	
}

plot_mu = function(x){
	
	x %>%
		# Get samples
		gather_samples(mu_softmax[gene_idx] ) %>%
		mean_qi() %>%
		ungroup() %>%
	
		# Add gene names
		left_join(
			tibble(
				gene_idx = 1:ncol(y),
				gene =     colnames(y)
			),
			by = "gene_idx"
		) %>%
		
		# Attach real y
			left_join(
				tibble(
					gene_idx = 1:length(!!real_mean),
					real =     !!real_mean
				),
				by = "gene_idx"
			) %>%
			
		# softmax real y
		mutate(real = real/sum(real)) %>%
		
		# Plot
		ggplot(aes(x=gene_idx, y=real, group=interaction(gene_idx))) +
		geom_errorbar(aes(ymin=conf.low, ymax=conf.high), width = 0) +
		geom_point(color="red") +
		geom_point(aes(x=gene_idx, y=real), color="green") +
		theme_bw()
	
}

plot_inference = function(plist, title){
	
	n <- length(plist)
	nCol <- floor(sqrt(n))
	do.call("grid.arrange", c(plist, ncol=nCol))
	
}

color_scheme_set("darkgray")
np = nuts_params(obj_logNormal_multinomial$fit)
lp = log_posterior(obj_logNormal_multinomial$fit)
mcmc_pairs(
  as.array(obj_logNormal_multinomial$fit),
	regex_pars  =c("mu\\[(1|2)\\]", "alpha_z\\[(1|2),1\\]", "^sigma" ),
  off_diag_fun = "hex",
  condition = pairs_condition(nuts = "lp__"),
  lp = lp,
  np = np,
  np_style = pairs_style_np(div_color = "firebrick",
                            td_color = "blue",
                            td_size = 0.5),
  # for demonstration purposes, set max_treedepth to a value that will
  # result in at least a few max treedepth warnings
  max_treedepth = with(np, -1 + max(Value[Parameter == "treedepth__"]))
)

```

# Multinomial pure

```{r Multinomial pure, results='hide', include=FALSE, cache=TRUE}

y = foreach(times = 1:samples, .combine = bind_cols) %do% {
	
	rates =  real_mean

	data.frame(
		rmultinom(
			1,
			exposure,
			rates/sum(rates)
		)
	
)
} %>% as_tibble() %>% setNames(as.character(1:samples)) %>%
	# Transpose
	mutate(gene = 1:length(real_mean)) %>% gather(sample, value, -gene) %>% spread(gene, value ) %>% select(-sample)


obj_pure = multinomial_pure()
obj_logNormal_multinomial = logNormal_multinomial()
obj_over_overdispersed = multinomial_over_overdispersed()
obj_dirichlet_multinomial = dirichlet_multinomial()
obj_negative_binomial = negative_binomial()

```

```{r plot pure}

grid.arrange(plot_gen(obj_pure$getn), plot_mu(obj_pure$fit), top="Multinomial")
grid.arrange(plot_gen(obj_logNormal_multinomial$getn), plot_mu(obj_logNormal_multinomial$fit), top="Multinomial overdispersed")
grid.arrange(plot_gen(obj_over_overdispersed$getn), plot_mu(obj_over_overdispersed$fit), top="Multinomial over overdispersed")
grid.arrange(plot_gen(obj_dirichlet_multinomial$getn), plot_mu(obj_dirichlet_multinomial$fit), top="Dirichlet multinomial")
grid.arrange(plot_gen(obj_negative_binomial$getn), plot_mu(obj_negative_binomial$fit), top="Negative binomial")

```

# Multinomial overdspersed

```{r Multinomial overdspersed, results='hide', include=FALSE, cache=TRUE}
y = foreach(times = 1:samples, .combine = bind_cols) %do% {
	
	rates = rnbinom( length(real_mean), mu = real_mean, size = 100) 
	
	data.frame(
		rmultinom(
			1,
			exposure,
			rates/sum(rates)
		)
		
	)
} %>% as_tibble() %>% setNames(as.character(1:samples)) %>%
	# Transpose
	mutate(gene = 1:length(real_mean)) %>% gather(sample, value, -gene) %>% spread(gene, value ) %>% select(-sample)


obj_pure = multinomial_pure()
obj_logNormal_multinomial = logNormal_multinomial()
obj_over_overdispersed = multinomial_over_overdispersed()
obj_dirichlet_multinomial = dirichlet_multinomial()
obj_negative_binomial = negative_binomial()

```

```{r plot overdispersed}

grid.arrange(plot_gen(obj_pure$getn), plot_mu(obj_pure$fit), top="Multinomial")
grid.arrange(plot_gen(obj_logNormal_multinomial$getn), plot_mu(obj_logNormal_multinomial$fit), top="Multinomial overdispersed")
grid.arrange(plot_gen(obj_over_overdispersed$getn), plot_mu(obj_over_overdispersed$fit), top="Multinomial over overdispersed")
grid.arrange(plot_gen(obj_dirichlet_multinomial$getn), plot_mu(obj_dirichlet_multinomial$fit), top="Dirichlet multinomial")
grid.arrange(plot_gen(obj_negative_binomial$getn), plot_mu(obj_negative_binomial$fit), top="Negative binomial")

```

# Multinomial over-overdispersed 

Here we have the overdispersion that increase proportionally with the expression value

```{r Multinomial over-overdispersed, results='hide', include=FALSE, cache=TRUE }
y = foreach(times = 1:samples, .combine = bind_cols) %do% {
	
	rates = rnbinom( length(real_mean), mu = real_mean, size = 10 / (0.01 * real_mean) ) 
	
	data.frame(
		rmultinom(
			1,
			exposure,
			rates/sum(rates)
		)
		
	)
} %>% as_tibble() %>% setNames(as.character(1:samples)) %>%
	# Transpose
	mutate(gene = 1:length(real_mean)) %>% gather(sample, value, -gene) %>% spread(gene, value ) %>% select(-sample)

obj_pure = multinomial_pure()
obj_logNormal_multinomial = logNormal_multinomial()
obj_over_overdispersed = multinomial_over_overdispersed()
obj_dirichlet_multinomial = dirichlet_multinomial()
obj_negative_binomial = negative_binomial()

```

```{r plot over overdispersed}

grid.arrange(plot_gen(obj_pure$getn), plot_mu(obj_pure$fit), top="Multinomial")
grid.arrange(plot_gen(obj_logNormal_multinomial$getn), plot_mu(obj_logNormal_multinomial$fit), top="Multinomial overdispersed")
grid.arrange(plot_gen(obj_over_overdispersed$getn), plot_mu(obj_over_overdispersed$fit), top="Multinomial over overdispersed")
grid.arrange(plot_gen(obj_dirichlet_multinomial$getn), plot_mu(obj_dirichlet_multinomial$fit), top="Dirichlet multinomial")
grid.arrange(plot_gen(obj_negative_binomial$getn), plot_mu(obj_negative_binomial$fit), top="Negative binomial")

```

