// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_noprior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_noprior_both_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_relaxprior_genqplot_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_tighterprior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_tightprior_inflect_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_one_gene_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_scale_factor_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DE_sigmoid_scale_factor_no_beta_prior_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_1_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_noprior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_noprior_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_noprior_both_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_noprior_both_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_relaxprior_genqplot_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_relaxprior_genqplot_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_tighterprior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_tighterprior_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_tightprior_inflect_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_hierarchical_tightprior_inflect_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_one_gene_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_one_gene_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_scale_factor_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_scale_factor_mod, 0},
    {"_rcpp_module_boot_stan_fit4DE_sigmoid_scale_factor_no_beta_prior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DE_sigmoid_scale_factor_no_beta_prior_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_TABI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
