# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("DE_sigmoid", "DE_sigmoid_hierarchical", "DE_sigmoid_hierarchical_1", "DE_sigmoid_hierarchical_noprior", "DE_sigmoid_hierarchical_noprior_both", "DE_sigmoid_hierarchical_relaxprior_genqplot", "DE_sigmoid_hierarchical_tighterprior", "DE_sigmoid_hierarchical_tightprior_inflect", "DE_sigmoid_one_gene", "DE_sigmoid_scale_factor", "DE_sigmoid_scale_factor_no_beta_prior")

# load each stan module
Rcpp::loadModule("stan_fit4DE_sigmoid_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_1_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_noprior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_noprior_both_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_relaxprior_genqplot_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_tighterprior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_tightprior_inflect_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_factor_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_factor_no_beta_prior_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
