# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("DE_sigmoid", "DE_sigmoid_Isobel_clean", "DE_sigmoid_fixed_log_space_fit_vert_trans", "DE_sigmoid_one_gene", "DE_sigmoid_one_gene_log_space", "DE_sigmoid_one_gene_test", "DE_sigmoid_one_gene_vert_log_space", "DE_sigmoid_one_gene_vert_log_space_od", "DE_sigmoid_one_gene_vert_trans", "DE_sigmoid_one_gene_vert_trans_corrected", "DE_sigmoid_one_gene_vert_trans_corrected_1", "DE_sigmoid_scale_factor", "DE_sigmoid_scale_factor_no_beta_prior", "DE_sigmoid_serial", "test_names")

# load each stan module
Rcpp::loadModule("stan_fit4DE_sigmoid_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_Isobel_clean_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_fixed_log_space_fit_vert_trans_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_log_space_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_test_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_vert_log_space_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_vert_log_space_od_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_vert_trans_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_vert_trans_corrected_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_vert_trans_corrected_1_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_factor_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_factor_no_beta_prior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_serial_mod", what = TRUE)
Rcpp::loadModule("stan_fit4test_names_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
