# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("DE_sigmoid", "DE_sigmoid_Isobel_clean", "DE_sigmoid_hierarchical", "DE_sigmoid_hierarchical_1", "DE_sigmoid_hierarchical_noprior", "DE_sigmoid_hierarchical_noprior_both", "DE_sigmoid_one_gene", "DE_sigmoid_one_gene_test", "DE_sigmoid_scale_factor", "DE_sigmoid_scale_factor_no_beta_prior", "DE_sigmoid_scale_test", "DE_sigmoid_serial", "DE_sigmoid_try", "DE_sigmoid_try_1", "DE_sigmoid_try_10", "DE_sigmoid_try_11", "DE_sigmoid_try_12", "DE_sigmoid_try_13", "DE_sigmoid_try_14", "DE_sigmoid_try_15", "DE_sigmoid_try_16", "DE_sigmoid_try_2", "DE_sigmoid_try_3", "DE_sigmoid_try_4", "DE_sigmoid_try_5", "DE_sigmoid_try_6", "DE_sigmoid_try_7", "DE_sigmoid_try_8", "DE_sigmoid_try_9", "test_names")

# load each stan module
Rcpp::loadModule("stan_fit4DE_sigmoid_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_Isobel_clean_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_1_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_noprior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_hierarchical_noprior_both_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_one_gene_test_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_factor_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_factor_no_beta_prior_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_scale_test_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_serial_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_1_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_10_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_11_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_12_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_13_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_14_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_15_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_16_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_2_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_3_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_5_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_6_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_7_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_8_mod", what = TRUE)
Rcpp::loadModule("stan_fit4DE_sigmoid_try_9_mod", what = TRUE)
Rcpp::loadModule("stan_fit4test_names_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
